### PR TITLE
Updated to 1.1

### PR DESCRIPTION
**Pull request by irperez**
Updated to Akka 1.1

### CODE REVIEW

**Comment by Danthar** [comment]
This PR is missing the Release_notes update

**Comment by irperez** [comment]
Should I put Today's date in the release notes?

**Comment by Danthar** [comment]
Yes. In the same way the previous versions are mentioned. This is important because our CI script looks at this statement.

Also, i am going to wait with merging this PR. Version 1.1.1 is right around the corner. Should come tonight or tomorrow. So i think its worth waiting for that version and upgrade the repo to that instead of doing a quick in between release.

**Comment by irperez** [comment]
Ok sounds good.

**Comment by Danthar** [comment]
Hi @irperez Are you willing to update this PR to 1.1.1 ? Then ill do a push to master afterwards.

**Comment by irperez** [comment]
I'm willing.  I'll try to get it tonight.

**Comment by irperez** [comment]
I've updated to the latest.  I've also updated the release notes following the same pattern.  Let me know if I need to modify anything else.

**Comment by irperez** [comment]
Hold on, I just noticed that the SharedAssemblyInfo.cs file is versioned in line with the akka version.  Shall I update this as well?

`
[assembly: AssemblyCompanyAttribute("Akka.NET Team")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2013-2016 Akka.NET Team")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.7.0")]
[assembly: AssemblyFileVersionAttribute("1.0.7.0")]
`

**Comment by Danthar** [comment]
If you call the `Build.cmd BuildRelease` command, it should update the assemblyinfo automatically. You can go ahead and commit those changes to the PR as well.

**Comment by irperez** [comment]
Wait, I may have screwed this up.  Should I update on the master branch or the dev?  This is currently on the dev branch.

**Comment by Danthar** [comment]
Dev is perfect. We first push to dev. Then i usually rebase the latest changes from dev in to master locally and push a PR to master.

That way dev is identical to master, and you wont have strange merge errors or whatnot when updating master for another release.

**Pull request merged**
